### PR TITLE
minor typo

### PR DESCRIPTION
**Pull request by canercandan**
`cd` bad directory name in the example

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment "._ok\W+to\W+test._"

**Comment by jannyHou** [comment]
Hi @canercandan Thanks for your correction! Can you sign our contributor License Agreement first? otherwise I could not merge your pr, thanks

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment "._ok\W+to\W+test._"

**Comment by jannyHou** [comment]
Thank you so much for pointing out the typo, but the pr could only be merged after you sign the agreement. Since it's a minor change I fixed typos in https://github.com/strongloop/loopback-example-relations/pull/32. 

Thanks for understanding:)

**Pull request closed without merging**
