### PR TITLE
Update example to use LoopBack 3.x

### PR DESCRIPTION
**Pull request by 0candy**
Connect to https://github.com/strongloop/loopback/issues/2772

### CODE REVIEW

**Comment by 0candy** [comment]
@bajtos @superkhau PTAL

**Review by superkhau — APPROVED** [review]

**Review by bajtos — APPROVED** [review]

**Comment by bajtos** [comment]
It makes me wonder why CIS did not run any build jobs? cc @rmg

**Comment by rmg** [comment]
There isn't much of a paper trail, but the commit that removed all the example repos from CI is dated June 14. There's probably a discussion on Slack about it.

**Comment by superkhau** [comment]
Cross referencing from Slack, the commit https://github.ibm.com/apimesh/ci/commit/bc7a72bc60e2ccf4656de6548338e0efd4caa7a0 is the one that removed examples off CIS awhile ago.

I'm proposing we keep it that way (for now) so we can keep 2.x examples on 2.x branches as part of the upgrade because git doesn't allow multiple tags with the same names over branches (2.x tags on two branches like `mysql` and `postgresql` for multi branch examples like `loopback-connector-database`.

Or at least until we figure out a strategy for maintaining 3x/2x examples (have had some discussions with @0candy and @crandmck, direction is not concrete yet).

**Pull request merged**
